### PR TITLE
Add alias for Speedtest, and add wish.com status

### PR DESCRIPTION
**Pull request by BlueWoIf**

### CODE REVIEW

**Comment by BlueWoIf** [comment]
accccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeepppppppppppppppppppppppppptttttttttttttttttt

**Comment by BlueWoIf** [comment]
nowww

**Comment by BlueWoIf** [comment]
a
c
c
e
p
t

p
l
s

a
f
t
e
r

l
u
n
c
h

:
D

**Comment by thechickennagget** [comment]
Whats going on

**Pull request merged**
